package f_exception;

class Test{
	static void method() {
		throw new Exception();
	}
	public static void main( String [] args ) {   
		try{
			method();
		} catch( Exception ex ) {
			System.out.println("예외처리");
		} 
	}
}